apiVersion: v1
kind: Service
metadata:
  name: mockoon-service
spec:
  selector:
    app: mockoon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: socketio-service
spec:
  selector:
    app: socketio-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
